Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,7 +1,7 @@
 name: test secrets
 
 on:
-  # push:
+  push:
   workflow_dispatch:
 
 env:
@@ -11,40 +11,46 @@ env:
 jobs:
   test-job:
     runs-on: ubuntu-latest
+    environment: dev
     container:
       image: composer
     steps:
       - name: print name
+        env:
+          NAME: vardhan
         run: echo "$NAME"
 
-      - name: print env
-        run: |-
-          if [ "${{ github.ref_name }}" == "main" ]; then
-            export AWS_ECS_SERVICE_NAME="worker-cdb-export-v3-int"
-            export AWS_ECS_CLUSTER_NAME="DigitalEngine-int"
-          elif [ "${{ github.ref_name }}" == "v3-staging" ]; then
-            export AWS_ECS_SERVICE_NAME="worker-cdb-export-v3-staging"
-            export AWS_ECS_CLUSTER_NAME="DigitalEngine-staging"
-          elif [ "${{ github.ref_name }}" == "v3-prod" ]; then
-            export AWS_ECS_SERVICE_NAME="worker-cdb-export-v3-prod"
-            export AWS_ECS_CLUSTER_NAME="DigitalEngine-prod"
-          else
-            echo "Error: Unsupported branch for ECS deployment"
-            exit 1
-          fi
-          echo "Using ECS Cluster: $AWS_ECS_CLUSTER_NAME"
-          echo "Using ECS Service: $AWS_ECS_SERVICE_NAME"
-          echo "AWS_ECS_SERVICE_NAME=$AWS_ECS_SERVICE_NAME" >> $GITHUB_ENV
-          export IMAGE_NAME="HARSHA"
-          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
+      - name: Print dev Environment variable
+        run: echo "${{ vars.NAME }}"
 
-      - name: out
-        run: |-
-          echo "$AWS_ECS_SERVICE_NAME" > service.txt
-      - name: test 2
-        run: |
-          echo "${{ github.event.repository.name }}" >> output.txt
-          echo "Using Service: $AWS_ECS_SERVICE_NAME"
-          echo "Using Image Name: $IMAGE_NAME"
+      # - name: print env
+      #   run: |-
+      #     if [ "${{ github.ref_name }}" == "main" ]; then
+      #       export AWS_ECS_SERVICE_NAME="worker-cdb-export-v3-int"
+      #       export AWS_ECS_CLUSTER_NAME="DigitalEngine-int"
+      #     elif [ "${{ github.ref_name }}" == "v3-staging" ]; then
+      #       export AWS_ECS_SERVICE_NAME="worker-cdb-export-v3-staging"
+      #       export AWS_ECS_CLUSTER_NAME="DigitalEngine-staging"
+      #     elif [ "${{ github.ref_name }}" == "v3-prod" ]; then
+      #       export AWS_ECS_SERVICE_NAME="worker-cdb-export-v3-prod"
+      #       export AWS_ECS_CLUSTER_NAME="DigitalEngine-prod"
+      #     else
+      #       echo "Error: Unsupported branch for ECS deployment"
+      #       exit 1
+      #     fi
+      #     echo "Using ECS Cluster: $AWS_ECS_CLUSTER_NAME"
+      #     echo "Using ECS Service: $AWS_ECS_SERVICE_NAME"
+      #     echo "AWS_ECS_SERVICE_NAME=$AWS_ECS_SERVICE_NAME" >> $GITHUB_ENV
+      #     export IMAGE_NAME="HARSHA"
+      #     echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
+
+      # - name: out
+      #   run: |-
+      #     echo "$AWS_ECS_SERVICE_NAME" > service.txt
+      # - name: test 2
+      #   run: |
+      #     echo "${{ github.event.repository.name }}" >> output.txt
+      #     echo "Using Service: $AWS_ECS_SERVICE_NAME"
+      #     echo "Using Image Name: $IMAGE_NAME"
           ls -l
           cat service.txt
